### ISSUE TITLE
Allow caching based on cwd and/or env

### ISSUE THREAD

**Issue by mdom** [kseistrup/memx#1]
This is a great idea! I just see a small problem with  using it ...  the output of a program often depends on more than just the command line. Would it be possible to optionally cache based on the environment or the current working path? Something like `--context path` or `--context path,env,args` with _args_ as default?

**Comment by kseistrup** [comment]
Thanks for reporting this.

`$CWD` should of course be a part of the individual cache directory hash. I will implement this later today.

When it comes to context, I would prefer to simply implement this as a free form string so that you can say

```sh
$ memx --context "whatever you like" -- cmd args…
```
and the string `"whatever you like"` would become a part of the directory hash. This means that you can run the same command from the same directory and still have separate output (the context could be hour of the day or day of the week or something entirely different, it's all up to the user). Would such an implement­ation satisfy your need, or did you have something else in mind?

**Comment by mdom** [comment]
On Mon, Sep 19, 2016 at 03:15:14AM -0700, Klaus Alexander Seistrup wrote:
> `$CWD` should of course be a part of the individual cache directory hash. I will implement this later today.

Great, thanks!

> When it comes to context, I would prefer to simply implement this as a free form string so that you can say
> 
> ```sh
> $ memx --context "whatever you like" -- cmd args…
> ```
> and the string `"whatever you like"` would become a part of the directory hash. This means that you can run the same command from the same directory and still have separate output (the context could be hour of the day or day of the week or something entirely different, it's all up to the user). Would such an implement­ation satisfy your need, or did you have something else in mind?

No, that sounds perfect.

Cheers, Mario

**Comment by kseistrup** [comment]
CWD is now taken into account only if COMMAND is a relative path, the rationale being that one should be able to have identical COMMAND names in different directories and be able to cd to such a directory and run `./COMMAND` with potentially different outputs (the same goes for `somedir/COMMAND`), whereas CWD is ignored for `/path/to/COMMAND`. Obviously this approach will fail miserably for COMMANDs like `/usr/bin/ls` (and succeed for `ls`).

If anybody has _practical_ examples that show that this approach has serious consequences, please chime in below.
